# -*- coding: utf-8 -*-
"""Frontend.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EPm01Jrh9gZEiD6d7varrJWRNHawRe0X
"""

#from google.colab import files
#uploaded = files.upload()

import joblib # type: ignore

model = joblib.load('/Users/ADMIN/Desktop/MLSN/my_model.joblib')

import streamlit as st # type: ignore
import numpy as np # type: ignore

st.title("Injury Prediction Model")
st.write("Enter player metrics below to predict Injury Next Season:")
Sprint_Speed_10m_s = st.number_input("Sprint Speed athlete")
Sleep_Hours_Per_Night = st.number_input("How much the athletes sleep every night")
Stress_Level_Score = st.number_input("Stress that the athletes experience")
Warmup_Routine_Adherence = st.selectbox(
    "Warmup Routine Adherence",
    ["Yes", "No"]
)
Warmup_Routine_Adherence = 1 if Warmup_Routine_Adherence == "Yes" else 0
Total_Workload = st.number_input("Total hours atheltes work outside of soccer")
Injuries_Per_Season = st.number_input("Injuries experienced in previous seasons")

features = np.array([
    Sprint_Speed_10m_s,
    Sleep_Hours_Per_Night,
    Stress_Level_Score,
    Warmup_Routine_Adherence,
    Total_Workload,
    Injuries_Per_Season
]).reshape(1, -1)

if st.button("Predict Injury Next Season"):
    prediction = model.predict(features)[0]

    if prediction == 1:
        st.error("High Risk: Player likely injured next season.")
        if Sleep_Hours_Per_Night < 6:
            st.error("Get more sleep")
        if Warmup_Routine_Adherence == 0:
            st.error("Do warmup regularly!!")
        if Total_Workload > 10:
            st.error("Balance your work and personal life")
    
    
    else:
        st.success("Low Risk: Player unlikely to be injured next season.")
